version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: cm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 10

  pulsar:
    image: apachepulsar/pulsar:4.1.0
    container_name: cm-pulsar
    command: ["bin/pulsar", "standalone"]
    restart: unless-stopped
    ports:
      - "6650:6650"
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/admin/v2/brokers/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cm-app
    depends_on:
      postgres:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/appdb
      PULSAR_SERVICE_URL: pulsar://pulsar:6650
      PULSAR_NAMESPACE: public/default
      FLASK_ENV: production
      PYTHONPATH: /app/src
    volumes:
      - ./src:/app/src:ro
    ports:
      - "5000:5000"
    command: >
      bash -lc "
      gunicorn 'campaign_management.main:create_app()' -b 0.0.0.0:5000 -w 2
      "
    restart: unless-stopped

  campaigns-projection-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cm-projection-consumer
    depends_on:
      postgres:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/appdb
      PULSAR_SERVICE_URL: pulsar://pulsar:6650
      PULSAR_NAMESPACE: public/default
      PYTHONPATH: /app/src
    volumes:
      - ./src:/app/src:ro
    command: |
      bash -lc '
      python - <<'"'"'PY'"'"'
      from campaign_management.main import create_app
      from campaign_management.infraestructura.event_consumer_service import event_consumer_service
      app = create_app()
      with app.app_context():
          event_consumer_service.start_consuming()
      PY
      '
    restart: unless-stopped

  outbox-dispatcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cm-outbox-dispatcher
    depends_on:
      postgres:
        condition: service_healthy
      pulsar:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/appdb
      PULSAR_SERVICE_URL: pulsar://pulsar:6650
      PULSAR_NAMESPACE: campaign-management/events
      PYTHONPATH: /app/src
    volumes:
      - ./src:/app/src:ro
    command: >
      bash -lc "
      python -m campaign_management.infraestructura.outbox.dispatcher
      "
    restart: unless-stopped

volumes:
  pg_data:
